export const CHANGE_VISITED_STATE = 'CHANGE_VISITED_STATE';
export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';

// sign-up
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// logout
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
